# Generated by Django 4.2.7 on 2026-03-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_shorturl_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='link_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
